// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArZXVu-Kn5_BlfyRjcw-nCNZGFaRoW6so',
    appId: '1:848300238155:web:9094eee0fca194fa4bf4ce',
    messagingSenderId: '848300238155',
    projectId: 'bytecodedb',
    authDomain: 'bytecodedb.firebaseapp.com',
    storageBucket: 'bytecodedb.appspot.com',
    measurementId: 'G-D91469GH07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1vu57xld4QYL0gom_aQtoj1eS7EHcb80',
    appId: '1:848300238155:android:639d1973495488754bf4ce',
    messagingSenderId: '848300238155',
    projectId: 'bytecodedb',
    storageBucket: 'bytecodedb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdFxY5Xk0ZfnJLt73hLH2fNKDSyA-5szA',
    appId: '1:848300238155:ios:c35316363f58254c4bf4ce',
    messagingSenderId: '848300238155',
    projectId: 'bytecodedb',
    storageBucket: 'bytecodedb.appspot.com',
    iosBundleId: 'com.example.bytecode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdFxY5Xk0ZfnJLt73hLH2fNKDSyA-5szA',
    appId: '1:848300238155:ios:c35316363f58254c4bf4ce',
    messagingSenderId: '848300238155',
    projectId: 'bytecodedb',
    storageBucket: 'bytecodedb.appspot.com',
    iosBundleId: 'com.example.bytecode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArZXVu-Kn5_BlfyRjcw-nCNZGFaRoW6so',
    appId: '1:848300238155:web:ea1c856905253b0a4bf4ce',
    messagingSenderId: '848300238155',
    projectId: 'bytecodedb',
    authDomain: 'bytecodedb.firebaseapp.com',
    storageBucket: 'bytecodedb.appspot.com',
    measurementId: 'G-BLW8JJ0R3W',
  );
}
